#![doc = r" Builder file for Peripheral access crate generated by svd2rust tool"]
use std::{env, fs::File, io::Write, path::PathBuf};
fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());

    // copy memory layout to build directory
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("memory.x"))
        .unwrap();
    println!("cargo:rerun-if-changed=memory.x");

    if env::var_os("CARGO_FEATURE_RT").is_some() {
        // copy interrupt table to build directory
        File::create(out.join("device.x"))
            .unwrap()
            .write_all(include_bytes!("device.x"))
            .unwrap();
        println!("cargo:rustc-link-search={}", out.display());
        println!("cargo:rerun-if-changed=device.x");
    }
    println!("cargo:rerun-if-changed=build.rs");
}
