#![doc = "Peripheral access API for EFR32MG22E224F512IM40 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
// don't print warnings when building the PAC
#![allow(warnings)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn CRYPTOACC();
    fn TRNG();
    fn PKE();
    fn SMU_SECURE();
    fn SMU_S_PRIVILEGED();
    fn SMU_NS_PRIVILEGED();
    fn EMU();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn TIMER3();
    fn TIMER4();
    fn RTCC();
    fn USART0_RX();
    fn USART0_TX();
    fn USART1_RX();
    fn USART1_TX();
    fn ICACHE0();
    fn BURTC();
    fn LETIMER0();
    fn SYSCFG();
    fn LDMA();
    fn LFXO();
    fn LFRCO();
    fn ULFRCO();
    fn GPIO_ODD();
    fn GPIO_EVEN();
    fn I2C0();
    fn I2C1();
    fn EMUDG();
    fn EMUSE();
    fn PRORTC();
    fn WDOG0();
    fn HFXO0();
    fn HFRCO0();
    fn CMU();
    fn AES();
    fn IADC();
    fn MSC();
    fn DPLL0();
    fn PDM();
    fn SW0();
    fn SW1();
    fn SW2();
    fn SW3();
    fn DCDC();
    fn EUART0_RX();
    fn EUART0_TX();

    // custom
    fn RFSENSE();
    fn AGC();
    fn BUFC();
    fn FRC_PRI();
    fn FRC();
    fn MODEM();
    fn PROTIMER();
    fn RAC_RSM();
    fn RAC_SEQ();
    fn RDMAILBOX();
    fn SYNTH();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 64] = [
    Vector {
        _handler: CRYPTOACC,
    },
    Vector { _handler: TRNG },
    Vector { _handler: PKE },
    Vector {
        _handler: SMU_SECURE,
    },
    Vector {
        _handler: SMU_S_PRIVILEGED,
    },
    Vector {
        _handler: SMU_NS_PRIVILEGED,
    },
    Vector { _handler: EMU },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: TIMER3 },
    Vector { _handler: TIMER4 },
    Vector { _handler: RTCC },
    Vector {
        _handler: USART0_RX,
    },
    Vector {
        _handler: USART0_TX,
    },
    Vector {
        _handler: USART1_RX,
    },
    Vector {
        _handler: USART1_TX,
    },
    Vector { _handler: ICACHE0 },
    Vector { _handler: BURTC },
    Vector { _handler: LETIMER0 },
    Vector { _handler: SYSCFG },
    Vector { _handler: LDMA },
    Vector { _handler: LFXO },
    Vector { _handler: LFRCO },
    Vector { _handler: ULFRCO },
    Vector { _handler: GPIO_ODD },
    Vector {
        _handler: GPIO_EVEN,
    },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _handler: EMUDG },
    Vector { _handler: EMUSE },
    Vector { _handler: AGC },
    Vector { _handler: BUFC },
    Vector { _handler: FRC_PRI },
    Vector { _handler: FRC },
    Vector { _handler: MODEM },
    Vector { _handler: PROTIMER },
    Vector { _handler: RAC_RSM },
    Vector { _handler: RAC_SEQ },
    Vector {
        _handler: RDMAILBOX,
    },
    Vector { _handler: RFSENSE },
    Vector { _handler: PRORTC },
    Vector { _handler: SYNTH },
    Vector { _handler: WDOG0 },
    Vector { _handler: HFXO0 },
    Vector { _handler: HFRCO0 },
    Vector { _handler: CMU },
    Vector { _handler: AES },
    Vector { _handler: IADC },
    Vector { _handler: MSC },
    Vector { _handler: DPLL0 },
    Vector { _handler: PDM },
    Vector { _handler: SW0 },
    Vector { _handler: SW1 },
    Vector { _handler: SW2 },
    Vector { _handler: SW3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DCDC },
    Vector {
        _handler: EUART0_RX,
    },
    Vector {
        _handler: EUART0_TX,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - CRYPTOACC"]
    CRYPTOACC = 0,
    #[doc = "1 - TRNG"]
    TRNG = 1,
    #[doc = "2 - PKE"]
    PKE = 2,
    #[doc = "3 - SMU_SECURE"]
    SMU_SECURE = 3,
    #[doc = "4 - SMU_S_PRIVILEGED"]
    SMU_S_PRIVILEGED = 4,
    #[doc = "5 - SMU_NS_PRIVILEGED"]
    SMU_NS_PRIVILEGED = 5,
    #[doc = "6 - EMU"]
    EMU = 6,
    #[doc = "7 - TIMER0"]
    TIMER0 = 7,
    #[doc = "8 - TIMER1"]
    TIMER1 = 8,
    #[doc = "9 - TIMER2"]
    TIMER2 = 9,
    #[doc = "10 - TIMER3"]
    TIMER3 = 10,
    #[doc = "11 - TIMER4"]
    TIMER4 = 11,
    #[doc = "12 - RTCC"]
    RTCC = 12,
    #[doc = "13 - USART0_RX"]
    USART0_RX = 13,
    #[doc = "14 - USART0_TX"]
    USART0_TX = 14,
    #[doc = "15 - USART1_RX"]
    USART1_RX = 15,
    #[doc = "16 - USART1_TX"]
    USART1_TX = 16,
    #[doc = "17 - ICACHE0"]
    ICACHE0 = 17,
    #[doc = "18 - BURTC"]
    BURTC = 18,
    #[doc = "19 - LETIMER0"]
    LETIMER0 = 19,
    #[doc = "20 - SYSCFG"]
    SYSCFG = 20,
    #[doc = "21 - LDMA"]
    LDMA = 21,
    #[doc = "22 - LFXO"]
    LFXO = 22,
    #[doc = "23 - LFRCO"]
    LFRCO = 23,
    #[doc = "24 - ULFRCO"]
    ULFRCO = 24,
    #[doc = "25 - GPIO_ODD"]
    GPIO_ODD = 25,
    #[doc = "26 - GPIO_EVEN"]
    GPIO_EVEN = 26,
    #[doc = "27 - I2C0"]
    I2C0 = 27,
    #[doc = "28 - I2C1"]
    I2C1 = 28,
    #[doc = "29 - EMUDG"]
    EMUDG = 29,
    #[doc = "30 - EMUSE"]
    EMUSE = 30,
    #[doc = "41 - PRORTC"]
    PRORTC = 41,
    #[doc = "43 - WDOG0"]
    WDOG0 = 43,
    #[doc = "44 - HFXO0"]
    HFXO0 = 44,
    #[doc = "45 - HFRCO0"]
    HFRCO0 = 45,
    #[doc = "46 - CMU"]
    CMU = 46,
    #[doc = "47 - AES"]
    AES = 47,
    #[doc = "48 - IADC"]
    IADC = 48,
    #[doc = "49 - MSC"]
    MSC = 49,
    #[doc = "50 - DPLL0"]
    DPLL0 = 50,
    #[doc = "51 - PDM"]
    PDM = 51,
    #[doc = "52 - SW0"]
    SW0 = 52,
    #[doc = "53 - SW1"]
    SW1 = 53,
    #[doc = "54 - SW2"]
    SW2 = 54,
    #[doc = "55 - SW3"]
    SW3 = 55,
    #[doc = "61 - DCDC"]
    DCDC = 61,
    #[doc = "62 - EUART0_RX"]
    EUART0_RX = 62,
    #[doc = "63 - EUART0_TX"]
    EUART0_TX = 63,

    // custom
    RFSENSE = 40,
    AGC = 31,
    BUFC = 32,
    FRC_PRI = 33,
    FRC = 34,
    MODEM = 35,
    PROTIMER = 36,
    RAC_RSM = 37,
    RAC_SEQ = 38,
    RDMAILBOX = 39,
    SYNTH = 42,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "BURAM_NS Registers"]
pub type BuramNs = crate::Periph<buram_ns::RegisterBlock, 0x5008_0000>;
impl core::fmt::Debug for BuramNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BuramNs").finish()
    }
}
#[doc = "BURAM_NS Registers"]
pub mod buram_ns;
#[doc = "BURAM_S Registers"]
pub type BuramS = crate::Periph<buram_s::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for BuramS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BuramS").finish()
    }
}
#[doc = "BURAM_S Registers"]
pub mod buram_s;
#[doc = "BURTC_NS Registers"]
pub type BurtcNs = crate::Periph<burtc_ns::RegisterBlock, 0x5006_4000>;
impl core::fmt::Debug for BurtcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BurtcNs").finish()
    }
}
#[doc = "BURTC_NS Registers"]
pub mod burtc_ns;
#[doc = "BURTC_S Registers"]
pub type BurtcS = crate::Periph<burtc_s::RegisterBlock, 0x4006_4000>;
impl core::fmt::Debug for BurtcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BurtcS").finish()
    }
}
#[doc = "BURTC_S Registers"]
pub mod burtc_s;
#[doc = "CMU_NS Registers"]
pub type CmuNs = crate::Periph<cmu_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for CmuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CmuNs").finish()
    }
}
#[doc = "CMU_NS Registers"]
pub mod cmu_ns;
#[doc = "CMU_S Registers"]
pub type CmuS = crate::Periph<cmu_s::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for CmuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CmuS").finish()
    }
}
#[doc = "CMU_S Registers"]
pub mod cmu_s;
#[doc = "CRYPTOACC_NS Registers"]
pub type CryptoaccNs = crate::Periph<cryptoacc_ns::RegisterBlock, 0x5c02_0000>;
impl core::fmt::Debug for CryptoaccNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccNs").finish()
    }
}
#[doc = "CRYPTOACC_NS Registers"]
pub mod cryptoacc_ns;
#[doc = "CRYPTOACC_NS_PKCTRL Registers"]
pub type CryptoaccNsPkctrl = crate::Periph<cryptoacc_ns_pkctrl::RegisterBlock, 0x5c02_2000>;
impl core::fmt::Debug for CryptoaccNsPkctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccNsPkctrl").finish()
    }
}
#[doc = "CRYPTOACC_NS_PKCTRL Registers"]
pub mod cryptoacc_ns_pkctrl;
#[doc = "CRYPTOACC_NS_RNGCTRL Registers"]
pub type CryptoaccNsRngctrl = crate::Periph<cryptoacc_ns_rngctrl::RegisterBlock, 0x5c02_1000>;
impl core::fmt::Debug for CryptoaccNsRngctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccNsRngctrl").finish()
    }
}
#[doc = "CRYPTOACC_NS_RNGCTRL Registers"]
pub mod cryptoacc_ns_rngctrl;
#[doc = "CRYPTOACC_S Registers"]
pub type CryptoaccS = crate::Periph<cryptoacc_s::RegisterBlock, 0x4c02_0000>;
impl core::fmt::Debug for CryptoaccS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccS").finish()
    }
}
#[doc = "CRYPTOACC_S Registers"]
pub mod cryptoacc_s;
#[doc = "CRYPTOACC_S_PKCTRL Registers"]
pub type CryptoaccSPkctrl = crate::Periph<cryptoacc_s_pkctrl::RegisterBlock, 0x4c02_2000>;
impl core::fmt::Debug for CryptoaccSPkctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccSPkctrl").finish()
    }
}
#[doc = "CRYPTOACC_S_PKCTRL Registers"]
pub mod cryptoacc_s_pkctrl;
#[doc = "CRYPTOACC_S_RNGCTRL Registers"]
pub type CryptoaccSRngctrl = crate::Periph<cryptoacc_s_rngctrl::RegisterBlock, 0x4c02_1000>;
impl core::fmt::Debug for CryptoaccSRngctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptoaccSRngctrl").finish()
    }
}
#[doc = "CRYPTOACC_S_RNGCTRL Registers"]
pub mod cryptoacc_s_rngctrl;
#[doc = "DCDC_NS Registers"]
pub type DcdcNs = crate::Periph<dcdc_ns::RegisterBlock, 0x5009_4000>;
impl core::fmt::Debug for DcdcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DcdcNs").finish()
    }
}
#[doc = "DCDC_NS Registers"]
pub mod dcdc_ns;
#[doc = "DCDC_S Registers"]
pub type DcdcS = crate::Periph<dcdc_s::RegisterBlock, 0x4009_4000>;
impl core::fmt::Debug for DcdcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DcdcS").finish()
    }
}
#[doc = "DCDC_S Registers"]
pub mod dcdc_s;
#[doc = "DPLL0_NS Registers"]
pub type Dpll0Ns = crate::Periph<dpll0_ns::RegisterBlock, 0x5001_c000>;
impl core::fmt::Debug for Dpll0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dpll0Ns").finish()
    }
}
#[doc = "DPLL0_NS Registers"]
pub mod dpll0_ns;
#[doc = "DPLL0_S Registers"]
pub type Dpll0S = crate::Periph<dpll0_s::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Dpll0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dpll0S").finish()
    }
}
#[doc = "DPLL0_S Registers"]
pub mod dpll0_s;
#[doc = "EMU_NS Registers"]
pub type EmuNs = crate::Periph<emu_ns::RegisterBlock, 0x5000_4000>;
impl core::fmt::Debug for EmuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EmuNs").finish()
    }
}
#[doc = "EMU_NS Registers"]
pub mod emu_ns;
#[doc = "EMU_S Registers"]
pub type EmuS = crate::Periph<emu_s::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for EmuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EmuS").finish()
    }
}
#[doc = "EMU_S Registers"]
pub mod emu_s;
#[doc = "EUART0_NS Registers"]
pub type Euart0Ns = crate::Periph<euart0_ns::RegisterBlock, 0x5a03_0000>;
impl core::fmt::Debug for Euart0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Euart0Ns").finish()
    }
}
#[doc = "EUART0_NS Registers"]
pub mod euart0_ns;
#[doc = "EUART0_S Registers"]
pub type Euart0S = crate::Periph<euart0_s::RegisterBlock, 0x4a03_0000>;
impl core::fmt::Debug for Euart0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Euart0S").finish()
    }
}
#[doc = "EUART0_S Registers"]
pub mod euart0_s;
#[doc = "FSRCO_NS Registers"]
pub type FsrcoNs = crate::Periph<fsrco_ns::RegisterBlock, 0x5001_8000>;
impl core::fmt::Debug for FsrcoNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FsrcoNs").finish()
    }
}
#[doc = "FSRCO_NS Registers"]
pub mod fsrco_ns;
#[doc = "FSRCO_S Registers"]
pub type FsrcoS = crate::Periph<fsrco_s::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for FsrcoS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FsrcoS").finish()
    }
}
#[doc = "FSRCO_S Registers"]
pub mod fsrco_s;
#[doc = "GPCRC_NS Registers"]
pub type GpcrcNs = crate::Periph<gpcrc_ns::RegisterBlock, 0x5008_8000>;
impl core::fmt::Debug for GpcrcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GpcrcNs").finish()
    }
}
#[doc = "GPCRC_NS Registers"]
pub mod gpcrc_ns;
#[doc = "GPCRC_S Registers"]
pub type GpcrcS = crate::Periph<gpcrc_s::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for GpcrcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GpcrcS").finish()
    }
}
#[doc = "GPCRC_S Registers"]
pub mod gpcrc_s;
#[doc = "GPIO_NS Registers"]
pub type GpioNs = crate::Periph<gpio_ns::RegisterBlock, 0x5003_c000>;
impl core::fmt::Debug for GpioNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GpioNs").finish()
    }
}
#[doc = "GPIO_NS Registers"]
pub mod gpio_ns;
#[doc = "GPIO_S Registers"]
pub type GpioS = crate::Periph<gpio_s::RegisterBlock, 0x4003_c000>;
impl core::fmt::Debug for GpioS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GpioS").finish()
    }
}
#[doc = "GPIO_S Registers"]
pub mod gpio_s;
#[doc = "HFRCO0_NS Registers"]
pub type Hfrco0Ns = crate::Periph<hfrco0_ns::RegisterBlock, 0x5001_0000>;
impl core::fmt::Debug for Hfrco0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hfrco0Ns").finish()
    }
}
#[doc = "HFRCO0_NS Registers"]
pub mod hfrco0_ns;
#[doc = "HFRCO0_S Registers"]
pub type Hfrco0S = crate::Periph<hfrco0_s::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Hfrco0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hfrco0S").finish()
    }
}
#[doc = "HFRCO0_S Registers"]
pub mod hfrco0_s;
#[doc = "HFXO0_NS Registers"]
pub type Hfxo0Ns = crate::Periph<hfxo0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Hfxo0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hfxo0Ns").finish()
    }
}
#[doc = "HFXO0_NS Registers"]
pub mod hfxo0_ns;
#[doc = "HFXO0_S Registers"]
pub type Hfxo0S = crate::Periph<hfxo0_s::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Hfxo0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hfxo0S").finish()
    }
}
#[doc = "HFXO0_S Registers"]
pub mod hfxo0_s;
#[doc = "I2C0_NS Registers"]
pub type I2c0Ns = crate::Periph<i2c0_ns::RegisterBlock, 0x5a01_0000>;
impl core::fmt::Debug for I2c0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0Ns").finish()
    }
}
#[doc = "I2C0_NS Registers"]
pub mod i2c0_ns;
#[doc = "I2C0_S Registers"]
pub type I2c0S = crate::Periph<i2c0_s::RegisterBlock, 0x4a01_0000>;
impl core::fmt::Debug for I2c0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0S").finish()
    }
}
#[doc = "I2C0_S Registers"]
pub mod i2c0_s;
#[doc = "I2C1_NS Registers"]
pub type I2c1Ns = crate::Periph<i2c1_ns::RegisterBlock, 0x5006_8000>;
impl core::fmt::Debug for I2c1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1Ns").finish()
    }
}
#[doc = "I2C1_NS Registers"]
pub mod i2c1_ns;
#[doc = "I2C1_S Registers"]
pub type I2c1S = crate::Periph<i2c1_s::RegisterBlock, 0x4006_8000>;
impl core::fmt::Debug for I2c1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1S").finish()
    }
}
#[doc = "I2C1_S Registers"]
pub mod i2c1_s;
#[doc = "IADC0_NS Registers"]
pub type Iadc0Ns = crate::Periph<iadc0_ns::RegisterBlock, 0x5a00_4000>;
impl core::fmt::Debug for Iadc0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iadc0Ns").finish()
    }
}
#[doc = "IADC0_NS Registers"]
pub mod iadc0_ns;
#[doc = "IADC0_S Registers"]
pub type Iadc0S = crate::Periph<iadc0_s::RegisterBlock, 0x4a00_4000>;
impl core::fmt::Debug for Iadc0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iadc0S").finish()
    }
}
#[doc = "IADC0_S Registers"]
pub mod iadc0_s;
#[doc = "ICACHE0_NS Registers"]
pub type Icache0Ns = crate::Periph<icache0_ns::RegisterBlock, 0x5003_4000>;
impl core::fmt::Debug for Icache0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icache0Ns").finish()
    }
}
#[doc = "ICACHE0_NS Registers"]
pub mod icache0_ns;
#[doc = "ICACHE0_S Registers"]
pub type Icache0S = crate::Periph<icache0_s::RegisterBlock, 0x4003_4000>;
impl core::fmt::Debug for Icache0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icache0S").finish()
    }
}
#[doc = "ICACHE0_S Registers"]
pub mod icache0_s;
#[doc = "LDMAXBAR_NS Registers"]
pub type LdmaxbarNs = crate::Periph<ldmaxbar_ns::RegisterBlock, 0x5004_4000>;
impl core::fmt::Debug for LdmaxbarNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LdmaxbarNs").finish()
    }
}
#[doc = "LDMAXBAR_NS Registers"]
pub mod ldmaxbar_ns;
#[doc = "LDMAXBAR_S Registers"]
pub type LdmaxbarS = crate::Periph<ldmaxbar_s::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for LdmaxbarS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LdmaxbarS").finish()
    }
}
#[doc = "LDMAXBAR_S Registers"]
pub mod ldmaxbar_s;
#[doc = "LDMA_NS Registers"]
pub type LdmaNs = crate::Periph<ldma_ns::RegisterBlock, 0x5004_0000>;
impl core::fmt::Debug for LdmaNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LdmaNs").finish()
    }
}
#[doc = "LDMA_NS Registers"]
pub mod ldma_ns;
#[doc = "LDMA_S Registers"]
pub type LdmaS = crate::Periph<ldma_s::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for LdmaS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LdmaS").finish()
    }
}
#[doc = "LDMA_S Registers"]
pub mod ldma_s;
#[doc = "LETIMER0_NS Registers"]
pub type Letimer0Ns = crate::Periph<letimer0_ns::RegisterBlock, 0x5a00_0000>;
impl core::fmt::Debug for Letimer0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Letimer0Ns").finish()
    }
}
#[doc = "LETIMER0_NS Registers"]
pub mod letimer0_ns;
#[doc = "LETIMER0_S Registers"]
pub type Letimer0S = crate::Periph<letimer0_s::RegisterBlock, 0x4a00_0000>;
impl core::fmt::Debug for Letimer0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Letimer0S").finish()
    }
}
#[doc = "LETIMER0_S Registers"]
pub mod letimer0_s;
#[doc = "LFRCO_NS Registers"]
pub type LfrcoNs = crate::Periph<lfrco_ns::RegisterBlock, 0x5002_4000>;
impl core::fmt::Debug for LfrcoNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LfrcoNs").finish()
    }
}
#[doc = "LFRCO_NS Registers"]
pub mod lfrco_ns;
#[doc = "LFRCO_S Registers"]
pub type LfrcoS = crate::Periph<lfrco_s::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for LfrcoS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LfrcoS").finish()
    }
}
#[doc = "LFRCO_S Registers"]
pub mod lfrco_s;
#[doc = "LFXO_NS Registers"]
pub type LfxoNs = crate::Periph<lfxo_ns::RegisterBlock, 0x5002_0000>;
impl core::fmt::Debug for LfxoNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LfxoNs").finish()
    }
}
#[doc = "LFXO_NS Registers"]
pub mod lfxo_ns;
#[doc = "LFXO_S Registers"]
pub type LfxoS = crate::Periph<lfxo_s::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for LfxoS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LfxoS").finish()
    }
}
#[doc = "LFXO_S Registers"]
pub mod lfxo_s;
#[doc = "MSC_NS Registers"]
pub type MscNs = crate::Periph<msc_ns::RegisterBlock, 0x5003_0000>;
impl core::fmt::Debug for MscNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MscNs").finish()
    }
}
#[doc = "MSC_NS Registers"]
pub mod msc_ns;
#[doc = "MSC_S Registers"]
pub type MscS = crate::Periph<msc_s::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for MscS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MscS").finish()
    }
}
#[doc = "MSC_S Registers"]
pub mod msc_s;
#[doc = "PDM_NS Registers"]
pub type PdmNs = crate::Periph<pdm_ns::RegisterBlock, 0x5009_8000>;
impl core::fmt::Debug for PdmNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PdmNs").finish()
    }
}
#[doc = "PDM_NS Registers"]
pub mod pdm_ns;
#[doc = "PDM_S Registers"]
pub type PdmS = crate::Periph<pdm_s::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for PdmS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PdmS").finish()
    }
}
#[doc = "PDM_S Registers"]
pub mod pdm_s;
#[doc = "PRORTC_NS Registers"]
pub type PrortcNs = crate::Periph<prortc_ns::RegisterBlock, 0xb800_0000>;
impl core::fmt::Debug for PrortcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PrortcNs").finish()
    }
}
#[doc = "PRORTC_NS Registers"]
pub mod prortc_ns;
#[doc = "PRORTC_S Registers"]
pub type PrortcS = crate::Periph<prortc_s::RegisterBlock, 0xa800_0000>;
impl core::fmt::Debug for PrortcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PrortcS").finish()
    }
}
#[doc = "PRORTC_S Registers"]
pub mod prortc_s;
#[doc = "PRS_NS Registers"]
pub type PrsNs = crate::Periph<prs_ns::RegisterBlock, 0x5003_8000>;
impl core::fmt::Debug for PrsNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PrsNs").finish()
    }
}
#[doc = "PRS_NS Registers"]
pub mod prs_ns;
#[doc = "PRS_S Registers"]
pub type PrsS = crate::Periph<prs_s::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for PrsS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PrsS").finish()
    }
}
#[doc = "PRS_S Registers"]
pub mod prs_s;
#[doc = "RADIOAES_NS Registers"]
pub type RadioaesNs = crate::Periph<radioaes_ns::RegisterBlock, 0x5400_0000>;
impl core::fmt::Debug for RadioaesNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RadioaesNs").finish()
    }
}
#[doc = "RADIOAES_NS Registers"]
pub mod radioaes_ns;
#[doc = "RADIOAES_S Registers"]
pub type RadioaesS = crate::Periph<radioaes_s::RegisterBlock, 0x4400_0000>;
impl core::fmt::Debug for RadioaesS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RadioaesS").finish()
    }
}
#[doc = "RADIOAES_S Registers"]
pub mod radioaes_s;
#[doc = "RTCC_NS Registers"]
pub type RtccNs = crate::Periph<rtcc_ns::RegisterBlock, 0x5800_0000>;
impl core::fmt::Debug for RtccNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RtccNs").finish()
    }
}
#[doc = "RTCC_NS Registers"]
pub mod rtcc_ns;
#[doc = "RTCC_S Registers"]
pub type RtccS = crate::Periph<rtcc_s::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for RtccS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RtccS").finish()
    }
}
#[doc = "RTCC_S Registers"]
pub mod rtcc_s;
#[doc = "SMU_NS Registers"]
pub type SmuNs = crate::Periph<smu_ns::RegisterBlock, 0x5400_8000>;
impl core::fmt::Debug for SmuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmuNs").finish()
    }
}
#[doc = "SMU_NS Registers"]
pub mod smu_ns;
#[doc = "SMU_NS_CFGNS Registers"]
pub type SmuNsCfgns = crate::Periph<smu_ns_cfgns::RegisterBlock, 0x5400_c000>;
impl core::fmt::Debug for SmuNsCfgns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmuNsCfgns").finish()
    }
}
#[doc = "SMU_NS_CFGNS Registers"]
pub mod smu_ns_cfgns;
#[doc = "SMU_S Registers"]
pub type SmuS = crate::Periph<smu_s::RegisterBlock, 0x4400_8000>;
impl core::fmt::Debug for SmuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmuS").finish()
    }
}
#[doc = "SMU_S Registers"]
pub mod smu_s;
#[doc = "SMU_S_CFGNS Registers"]
pub type SmuSCfgns = crate::Periph<smu_s_cfgns::RegisterBlock, 0x4400_c000>;
impl core::fmt::Debug for SmuSCfgns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SmuSCfgns").finish()
    }
}
#[doc = "SMU_S_CFGNS Registers"]
pub mod smu_s_cfgns;
#[doc = "SYSCFG_NS Registers"]
pub type SyscfgNs = crate::Periph<syscfg_ns::RegisterBlock, 0x5007_c000>;
impl core::fmt::Debug for SyscfgNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SyscfgNs").finish()
    }
}
#[doc = "SYSCFG_NS Registers"]
pub mod syscfg_ns;
#[doc = "SYSCFG_NS_CFGNS Registers"]
pub type SyscfgNsCfgns = crate::Periph<syscfg_ns_cfgns::RegisterBlock, 0x5007_8000>;
impl core::fmt::Debug for SyscfgNsCfgns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SyscfgNsCfgns").finish()
    }
}
#[doc = "SYSCFG_NS_CFGNS Registers"]
pub mod syscfg_ns_cfgns;
#[doc = "SYSCFG_S Registers"]
pub type SyscfgS = crate::Periph<syscfg_s::RegisterBlock, 0x4007_c000>;
impl core::fmt::Debug for SyscfgS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SyscfgS").finish()
    }
}
#[doc = "SYSCFG_S Registers"]
pub mod syscfg_s;
#[doc = "SYSCFG_S_CFGNS Registers"]
pub type SyscfgSCfgns = crate::Periph<syscfg_s_cfgns::RegisterBlock, 0x4007_8000>;
impl core::fmt::Debug for SyscfgSCfgns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SyscfgSCfgns").finish()
    }
}
#[doc = "SYSCFG_S_CFGNS Registers"]
pub mod syscfg_s_cfgns;
#[doc = "TIMER0_NS Registers"]
pub type Timer0Ns = crate::Periph<timer0_ns::RegisterBlock, 0x5004_8000>;
impl core::fmt::Debug for Timer0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0Ns").finish()
    }
}
#[doc = "TIMER0_NS Registers"]
pub mod timer0_ns;
#[doc = "TIMER0_S Registers"]
pub type Timer0S = crate::Periph<timer0_s::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for Timer0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0S").finish()
    }
}
#[doc = "TIMER0_S Registers"]
pub mod timer0_s;
#[doc = "TIMER1_NS Registers"]
pub type Timer1Ns = crate::Periph<timer1_ns::RegisterBlock, 0x5004_c000>;
impl core::fmt::Debug for Timer1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1Ns").finish()
    }
}
#[doc = "TIMER1_NS Registers"]
pub mod timer1_ns;
#[doc = "TIMER1_S Registers"]
pub type Timer1S = crate::Periph<timer1_s::RegisterBlock, 0x4004_c000>;
impl core::fmt::Debug for Timer1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1S").finish()
    }
}
#[doc = "TIMER1_S Registers"]
pub mod timer1_s;
#[doc = "TIMER2_NS Registers"]
pub type Timer2Ns = crate::Periph<timer2_ns::RegisterBlock, 0x5005_0000>;
impl core::fmt::Debug for Timer2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2Ns").finish()
    }
}
#[doc = "TIMER2_NS Registers"]
pub mod timer2_ns;
#[doc = "TIMER2_S Registers"]
pub type Timer2S = crate::Periph<timer2_s::RegisterBlock, 0x4005_0000>;
impl core::fmt::Debug for Timer2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2S").finish()
    }
}
#[doc = "TIMER2_S Registers"]
pub mod timer2_s;
#[doc = "TIMER3_NS Registers"]
pub type Timer3Ns = crate::Periph<timer3_ns::RegisterBlock, 0x5005_4000>;
impl core::fmt::Debug for Timer3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer3Ns").finish()
    }
}
#[doc = "TIMER3_NS Registers"]
pub mod timer3_ns;
#[doc = "TIMER3_S Registers"]
pub type Timer3S = crate::Periph<timer3_s::RegisterBlock, 0x4005_4000>;
impl core::fmt::Debug for Timer3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer3S").finish()
    }
}
#[doc = "TIMER3_S Registers"]
pub mod timer3_s;
#[doc = "TIMER4_NS Registers"]
pub type Timer4Ns = crate::Periph<timer4_ns::RegisterBlock, 0x5005_8000>;
impl core::fmt::Debug for Timer4Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer4Ns").finish()
    }
}
#[doc = "TIMER4_NS Registers"]
pub mod timer4_ns;
#[doc = "TIMER4_S Registers"]
pub type Timer4S = crate::Periph<timer4_s::RegisterBlock, 0x4005_8000>;
impl core::fmt::Debug for Timer4S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer4S").finish()
    }
}
#[doc = "TIMER4_S Registers"]
pub mod timer4_s;
#[doc = "ULFRCO_NS Registers"]
pub type UlfrcoNs = crate::Periph<ulfrco_ns::RegisterBlock, 0x5002_8000>;
impl core::fmt::Debug for UlfrcoNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UlfrcoNs").finish()
    }
}
#[doc = "ULFRCO_NS Registers"]
pub mod ulfrco_ns;
#[doc = "ULFRCO_S Registers"]
pub type UlfrcoS = crate::Periph<ulfrco_s::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for UlfrcoS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UlfrcoS").finish()
    }
}
#[doc = "ULFRCO_S Registers"]
pub mod ulfrco_s;
#[doc = "USART0_NS Registers"]
pub type Usart0Ns = crate::Periph<usart0_ns::RegisterBlock, 0x5005_c000>;
impl core::fmt::Debug for Usart0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0Ns").finish()
    }
}
#[doc = "USART0_NS Registers"]
pub mod usart0_ns;
#[doc = "USART0_S Registers"]
pub type Usart0S = crate::Periph<usart0_s::RegisterBlock, 0x4005_c000>;
impl core::fmt::Debug for Usart0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0S").finish()
    }
}
#[doc = "USART0_S Registers"]
pub mod usart0_s;
#[doc = "USART1_NS Registers"]
pub type Usart1Ns = crate::Periph<usart1_ns::RegisterBlock, 0x5006_0000>;
impl core::fmt::Debug for Usart1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1Ns").finish()
    }
}
#[doc = "USART1_NS Registers"]
pub mod usart1_ns;
#[doc = "USART1_S Registers"]
pub type Usart1S = crate::Periph<usart1_s::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for Usart1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1S").finish()
    }
}
#[doc = "USART1_S Registers"]
pub mod usart1_s;
#[doc = "WDOG0_NS Registers"]
pub type Wdog0Ns = crate::Periph<wdog0_ns::RegisterBlock, 0x5a01_8000>;
impl core::fmt::Debug for Wdog0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog0Ns").finish()
    }
}
#[doc = "WDOG0_NS Registers"]
pub mod wdog0_ns;
#[doc = "WDOG0_S Registers"]
pub type Wdog0S = crate::Periph<wdog0_s::RegisterBlock, 0x4a01_8000>;
impl core::fmt::Debug for Wdog0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog0S").finish()
    }
}
#[doc = "WDOG0_S Registers"]
pub mod wdog0_s;
#[doc = "DEVINFO Registers"]
pub type Devinfo = crate::Periph<devinfo::RegisterBlock, 0x0fe0_8000>;
impl core::fmt::Debug for Devinfo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Devinfo").finish()
    }
}
#[doc = "DEVINFO Registers"]
pub mod devinfo;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "BURAM_NS"]
    pub buram_ns: BuramNs,
    #[doc = "BURAM_S"]
    pub buram_s: BuramS,
    #[doc = "BURTC_NS"]
    pub burtc_ns: BurtcNs,
    #[doc = "BURTC_S"]
    pub burtc_s: BurtcS,
    #[doc = "CMU_NS"]
    pub cmu_ns: CmuNs,
    #[doc = "CMU_S"]
    pub cmu_s: CmuS,
    #[doc = "CRYPTOACC_NS"]
    pub cryptoacc_ns: CryptoaccNs,
    #[doc = "CRYPTOACC_NS_PKCTRL"]
    pub cryptoacc_ns_pkctrl: CryptoaccNsPkctrl,
    #[doc = "CRYPTOACC_NS_RNGCTRL"]
    pub cryptoacc_ns_rngctrl: CryptoaccNsRngctrl,
    #[doc = "CRYPTOACC_S"]
    pub cryptoacc_s: CryptoaccS,
    #[doc = "CRYPTOACC_S_PKCTRL"]
    pub cryptoacc_s_pkctrl: CryptoaccSPkctrl,
    #[doc = "CRYPTOACC_S_RNGCTRL"]
    pub cryptoacc_s_rngctrl: CryptoaccSRngctrl,
    #[doc = "DCDC_NS"]
    pub dcdc_ns: DcdcNs,
    #[doc = "DCDC_S"]
    pub dcdc_s: DcdcS,
    #[doc = "DPLL0_NS"]
    pub dpll0_ns: Dpll0Ns,
    #[doc = "DPLL0_S"]
    pub dpll0_s: Dpll0S,
    #[doc = "EMU_NS"]
    pub emu_ns: EmuNs,
    #[doc = "EMU_S"]
    pub emu_s: EmuS,
    #[doc = "EUART0_NS"]
    pub euart0_ns: Euart0Ns,
    #[doc = "EUART0_S"]
    pub euart0_s: Euart0S,
    #[doc = "FSRCO_NS"]
    pub fsrco_ns: FsrcoNs,
    #[doc = "FSRCO_S"]
    pub fsrco_s: FsrcoS,
    #[doc = "GPCRC_NS"]
    pub gpcrc_ns: GpcrcNs,
    #[doc = "GPCRC_S"]
    pub gpcrc_s: GpcrcS,
    #[doc = "GPIO_NS"]
    pub gpio_ns: GpioNs,
    #[doc = "GPIO_S"]
    pub gpio_s: GpioS,
    #[doc = "HFRCO0_NS"]
    pub hfrco0_ns: Hfrco0Ns,
    #[doc = "HFRCO0_S"]
    pub hfrco0_s: Hfrco0S,
    #[doc = "HFXO0_NS"]
    pub hfxo0_ns: Hfxo0Ns,
    #[doc = "HFXO0_S"]
    pub hfxo0_s: Hfxo0S,
    #[doc = "I2C0_NS"]
    pub i2c0_ns: I2c0Ns,
    #[doc = "I2C0_S"]
    pub i2c0_s: I2c0S,
    #[doc = "I2C1_NS"]
    pub i2c1_ns: I2c1Ns,
    #[doc = "I2C1_S"]
    pub i2c1_s: I2c1S,
    #[doc = "IADC0_NS"]
    pub iadc0_ns: Iadc0Ns,
    #[doc = "IADC0_S"]
    pub iadc0_s: Iadc0S,
    #[doc = "ICACHE0_NS"]
    pub icache0_ns: Icache0Ns,
    #[doc = "ICACHE0_S"]
    pub icache0_s: Icache0S,
    #[doc = "LDMAXBAR_NS"]
    pub ldmaxbar_ns: LdmaxbarNs,
    #[doc = "LDMAXBAR_S"]
    pub ldmaxbar_s: LdmaxbarS,
    #[doc = "LDMA_NS"]
    pub ldma_ns: LdmaNs,
    #[doc = "LDMA_S"]
    pub ldma_s: LdmaS,
    #[doc = "LETIMER0_NS"]
    pub letimer0_ns: Letimer0Ns,
    #[doc = "LETIMER0_S"]
    pub letimer0_s: Letimer0S,
    #[doc = "LFRCO_NS"]
    pub lfrco_ns: LfrcoNs,
    #[doc = "LFRCO_S"]
    pub lfrco_s: LfrcoS,
    #[doc = "LFXO_NS"]
    pub lfxo_ns: LfxoNs,
    #[doc = "LFXO_S"]
    pub lfxo_s: LfxoS,
    #[doc = "MSC_NS"]
    pub msc_ns: MscNs,
    #[doc = "MSC_S"]
    pub msc_s: MscS,
    #[doc = "PDM_NS"]
    pub pdm_ns: PdmNs,
    #[doc = "PDM_S"]
    pub pdm_s: PdmS,
    #[doc = "PRORTC_NS"]
    pub prortc_ns: PrortcNs,
    #[doc = "PRORTC_S"]
    pub prortc_s: PrortcS,
    #[doc = "PRS_NS"]
    pub prs_ns: PrsNs,
    #[doc = "PRS_S"]
    pub prs_s: PrsS,
    #[doc = "RADIOAES_NS"]
    pub radioaes_ns: RadioaesNs,
    #[doc = "RADIOAES_S"]
    pub radioaes_s: RadioaesS,
    #[doc = "RTCC_NS"]
    pub rtcc_ns: RtccNs,
    #[doc = "RTCC_S"]
    pub rtcc_s: RtccS,
    #[doc = "SMU_NS"]
    pub smu_ns: SmuNs,
    #[doc = "SMU_NS_CFGNS"]
    pub smu_ns_cfgns: SmuNsCfgns,
    #[doc = "SMU_S"]
    pub smu_s: SmuS,
    #[doc = "SMU_S_CFGNS"]
    pub smu_s_cfgns: SmuSCfgns,
    #[doc = "SYSCFG_NS"]
    pub syscfg_ns: SyscfgNs,
    #[doc = "SYSCFG_NS_CFGNS"]
    pub syscfg_ns_cfgns: SyscfgNsCfgns,
    #[doc = "SYSCFG_S"]
    pub syscfg_s: SyscfgS,
    #[doc = "SYSCFG_S_CFGNS"]
    pub syscfg_s_cfgns: SyscfgSCfgns,
    #[doc = "TIMER0_NS"]
    pub timer0_ns: Timer0Ns,
    #[doc = "TIMER0_S"]
    pub timer0_s: Timer0S,
    #[doc = "TIMER1_NS"]
    pub timer1_ns: Timer1Ns,
    #[doc = "TIMER1_S"]
    pub timer1_s: Timer1S,
    #[doc = "TIMER2_NS"]
    pub timer2_ns: Timer2Ns,
    #[doc = "TIMER2_S"]
    pub timer2_s: Timer2S,
    #[doc = "TIMER3_NS"]
    pub timer3_ns: Timer3Ns,
    #[doc = "TIMER3_S"]
    pub timer3_s: Timer3S,
    #[doc = "TIMER4_NS"]
    pub timer4_ns: Timer4Ns,
    #[doc = "TIMER4_S"]
    pub timer4_s: Timer4S,
    #[doc = "ULFRCO_NS"]
    pub ulfrco_ns: UlfrcoNs,
    #[doc = "ULFRCO_S"]
    pub ulfrco_s: UlfrcoS,
    #[doc = "USART0_NS"]
    pub usart0_ns: Usart0Ns,
    #[doc = "USART0_S"]
    pub usart0_s: Usart0S,
    #[doc = "USART1_NS"]
    pub usart1_ns: Usart1Ns,
    #[doc = "USART1_S"]
    pub usart1_s: Usart1S,
    #[doc = "WDOG0_NS"]
    pub wdog0_ns: Wdog0Ns,
    #[doc = "WDOG0_S"]
    pub wdog0_s: Wdog0S,
    #[doc = "DEVINFO"]
    pub devinfo: Devinfo,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            buram_ns: BuramNs::steal(),
            buram_s: BuramS::steal(),
            burtc_ns: BurtcNs::steal(),
            burtc_s: BurtcS::steal(),
            cmu_ns: CmuNs::steal(),
            cmu_s: CmuS::steal(),
            cryptoacc_ns: CryptoaccNs::steal(),
            cryptoacc_ns_pkctrl: CryptoaccNsPkctrl::steal(),
            cryptoacc_ns_rngctrl: CryptoaccNsRngctrl::steal(),
            cryptoacc_s: CryptoaccS::steal(),
            cryptoacc_s_pkctrl: CryptoaccSPkctrl::steal(),
            cryptoacc_s_rngctrl: CryptoaccSRngctrl::steal(),
            dcdc_ns: DcdcNs::steal(),
            dcdc_s: DcdcS::steal(),
            dpll0_ns: Dpll0Ns::steal(),
            dpll0_s: Dpll0S::steal(),
            emu_ns: EmuNs::steal(),
            emu_s: EmuS::steal(),
            euart0_ns: Euart0Ns::steal(),
            euart0_s: Euart0S::steal(),
            fsrco_ns: FsrcoNs::steal(),
            fsrco_s: FsrcoS::steal(),
            gpcrc_ns: GpcrcNs::steal(),
            gpcrc_s: GpcrcS::steal(),
            gpio_ns: GpioNs::steal(),
            gpio_s: GpioS::steal(),
            hfrco0_ns: Hfrco0Ns::steal(),
            hfrco0_s: Hfrco0S::steal(),
            hfxo0_ns: Hfxo0Ns::steal(),
            hfxo0_s: Hfxo0S::steal(),
            i2c0_ns: I2c0Ns::steal(),
            i2c0_s: I2c0S::steal(),
            i2c1_ns: I2c1Ns::steal(),
            i2c1_s: I2c1S::steal(),
            iadc0_ns: Iadc0Ns::steal(),
            iadc0_s: Iadc0S::steal(),
            icache0_ns: Icache0Ns::steal(),
            icache0_s: Icache0S::steal(),
            ldmaxbar_ns: LdmaxbarNs::steal(),
            ldmaxbar_s: LdmaxbarS::steal(),
            ldma_ns: LdmaNs::steal(),
            ldma_s: LdmaS::steal(),
            letimer0_ns: Letimer0Ns::steal(),
            letimer0_s: Letimer0S::steal(),
            lfrco_ns: LfrcoNs::steal(),
            lfrco_s: LfrcoS::steal(),
            lfxo_ns: LfxoNs::steal(),
            lfxo_s: LfxoS::steal(),
            msc_ns: MscNs::steal(),
            msc_s: MscS::steal(),
            pdm_ns: PdmNs::steal(),
            pdm_s: PdmS::steal(),
            prortc_ns: PrortcNs::steal(),
            prortc_s: PrortcS::steal(),
            prs_ns: PrsNs::steal(),
            prs_s: PrsS::steal(),
            radioaes_ns: RadioaesNs::steal(),
            radioaes_s: RadioaesS::steal(),
            rtcc_ns: RtccNs::steal(),
            rtcc_s: RtccS::steal(),
            smu_ns: SmuNs::steal(),
            smu_ns_cfgns: SmuNsCfgns::steal(),
            smu_s: SmuS::steal(),
            smu_s_cfgns: SmuSCfgns::steal(),
            syscfg_ns: SyscfgNs::steal(),
            syscfg_ns_cfgns: SyscfgNsCfgns::steal(),
            syscfg_s: SyscfgS::steal(),
            syscfg_s_cfgns: SyscfgSCfgns::steal(),
            timer0_ns: Timer0Ns::steal(),
            timer0_s: Timer0S::steal(),
            timer1_ns: Timer1Ns::steal(),
            timer1_s: Timer1S::steal(),
            timer2_ns: Timer2Ns::steal(),
            timer2_s: Timer2S::steal(),
            timer3_ns: Timer3Ns::steal(),
            timer3_s: Timer3S::steal(),
            timer4_ns: Timer4Ns::steal(),
            timer4_s: Timer4S::steal(),
            ulfrco_ns: UlfrcoNs::steal(),
            ulfrco_s: UlfrcoS::steal(),
            usart0_ns: Usart0Ns::steal(),
            usart0_s: Usart0S::steal(),
            usart1_ns: Usart1Ns::steal(),
            usart1_s: Usart1S::steal(),
            wdog0_ns: Wdog0Ns::steal(),
            wdog0_s: Wdog0S::steal(),
            devinfo: Devinfo::steal(),
        }
    }
}
// https://github.com/SiliconLabs/simplicity_sdk/blob/sisdk-2025.6/platform/Device/SiliconLabs/EFR32MG22/Include/efr32mg22e224f512im40.h#L144
pub const NVIC_PRIO_BITS: u8 = 4;
